# Generated by Django 3.0.7 on 2020-06-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200617_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='no address', max_length=300),
            preserve_default=False,
        ),
    ]
