# Generated by Django 3.0.7 on 2020-06-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200622_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='discount',
            field=models.IntegerField(default=0, max_length=50, verbose_name='Discount'),
        ),
    ]
