# Generated by Django 3.0.7 on 2020-06-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200622_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='discount',
            field=models.CharField(max_length=50, verbose_name='discount'),
        ),
    ]
