# Generated by Django 3.0.7 on 2020-06-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customer_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='discount',
            field=models.IntegerField(null=True, verbose_name='Discount'),
        ),
    ]
