# Generated by Django 3.0.7 on 2020-06-22 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200622_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='offer',
        ),
    ]
