# Generated by Django 3.0.7 on 2020-06-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_customer_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Discount'),
        ),
    ]
