# Generated by Django 3.0.7 on 2020-06-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200622_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='policy',
            field=models.FileField(default=True, upload_to='companies/policy', verbose_name='Company Policy'),
            preserve_default=False,
        ),
    ]
