# Generated by Django 3.0.7 on 2020-06-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='adv/images', verbose_name='Image Data')),
                ('title', models.TextField(max_length=30)),
                ('the_link', models.TextField(max_length=200)),
            ],
        ),
    ]
