# Generated by Django 3.0.7 on 2020-06-06 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.CharField(max_length=255)),
                ('contact_type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Companies')),
            ],
        ),
        migrations.RemoveField(
            model_name='companyurls',
            name='company',
        ),
        migrations.DeleteModel(
            name='CompanyNumbers',
        ),
        migrations.DeleteModel(
            name='CompanyUrls',
        ),
    ]
