# Generated by Django 3.0.7 on 2020-06-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20200606_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='logo',
            field=models.ImageField(upload_to='companies/images', verbose_name='Company Image'),
        ),
    ]
