# Generated by Django 3.0.7 on 2020-06-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_program_avgrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
