# Generated by Django 3.0.7 on 2020-06-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_program_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedprogram',
            name='rate',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
