# Generated by Django 3.0.7 on 2020-06-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20200611_1937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyContacts',
            new_name='Company_Contacts',
        ),
        migrations.RenameModel(
            old_name='ProgramPhotos',
            new_name='Program_Photos',
        ),
    ]
