# Generated by Django 3.0.7 on 2020-06-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200620_1249'),
        ('companies', '0004_auto_20200618_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontact',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_company_contact', to='users.Company'),
        ),
        migrations.AlterField(
            model_name='companyusermessage',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_company_user_message', to='users.Company'),
        ),
        migrations.AlterField(
            model_name='companyusermessage',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_company_user_message', to='users.Customer'),
        ),
        migrations.AlterField(
            model_name='program',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_program', to='users.Company'),
        ),
        migrations.AlterField(
            model_name='programphoto',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_photo_program', to='companies.Program'),
        ),
        migrations.AlterField(
            model_name='programreview',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_program_review', to='users.Customer'),
        ),
        migrations.AlterField(
            model_name='programreview',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_program_review', to='companies.Program'),
        ),
        migrations.AlterField(
            model_name='selectedprogram',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_selected_program', to='users.Company'),
        ),
        migrations.AlterField(
            model_name='selectedprogram',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_selected_program', to='users.Customer'),
        ),
        migrations.AlterField(
            model_name='selectedprogram',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_selected_program', to='companies.Program'),
        ),
    ]
