# Generated by Django 3.0.7 on 2020-06-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_companyusermessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
