# Generated by Django 3.0.7 on 2020-06-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_companyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedprogram',
            name='area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='selectedprogram',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
