# Generated by Django 3.0.7 on 2020-06-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_remove_programs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
