# Generated by Django 3.0.7 on 2020-06-24 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_auto_20200624_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedprogram',
            name='area',
            field=models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(5)]),
            preserve_default=False,
        ),
    ]
