# Generated by Django 3.0.7 on 2020-06-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_selected_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selected_programs',
            name='rate',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=5),
        ),
    ]
