# Generated by Django 3.0.7 on 2020-06-24 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20200624_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedprogram',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
