# Generated by Django 3.0.7 on 2020-06-24 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_auto_20200624_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedprogram',
            name='pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selectedprogram',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
