# Generated by Django 3.0.7 on 2020-06-14 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_auto_20200613_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='image',
        ),
    ]
